version: '3.8'
services:
  # redis:
  #   image: redis:6.2-alpine
  #   restart: always
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning
  #   volumes: 
  #     - cache:/data
  # mongo:
  #   container_name: mongo
  #   image: ${REG}mongo
  #   restart: always
  #   volumes:
  #     - mongo-data:/data
  #   ports:
  #     - 27017:27017
  #  redis:
  #    container_name: redis
  #    image: ${REG}redis
  #   restart: always
  #   volumes: 
  #     - cache:/data
  #   ports:
  #     - 6379:6379
  app:
    container_name: isss-backend
    restart: always
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    #image: isss-backend
    env_file: .env
    # environment:
    #   - PORT_http: 3000
    #   - PORT_https: 4000
    #   - HOST: "localhost"
    #   - BASE_URL: "127.0.0.1:9000/api/v1"
    #   #MONGODB_URL:mongodb://services.ariapa.com:27021/backend_isss?directConnection:true
    #   #MONGODB_URL:mongodb://192.168.1.145:27021/test?directConnection:true
    #   - MONGODB_URL: "mongodb://127.0.0.1:27019/test?directConnection=true"
    #   - REDIS_URL: "redis://127.0.0.1:6379"
    #   - JWT_SECRET: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY1NzA4ODI5NiwiaWF0IjoxNjU3MDg4Mjk2fQ.0Qoo9fGvlQAQ428j7jJqSKOw9UJK-iXVEdQLwuyYJpg
    #   - ELASTIC_SEARCH: "http://127.0.0.1:9200"
    #   - LOKI: "http://192.168.10.20:3100"
    #   - REQUEST_LOG_FORMAT: "combined"
    #   - sample_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZjI0N2JhOWQ5NmEzNjkxMDZkYzIxYiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY2MzkyNDExMCwiaWF0IjoxNjYxMzMyMTEwfQ.tNZmNHIeZTgUkq4moSPx3snL6PINc3e5uf4PWQ_YD0c
    #   - env: development
    #   - WEB_STREAM: "http://192.168.10.20:8083/testcamera/"
    #   - REQUEST_LOG_FILE: ./logs/request.log
    #   - API_AI_REDIS_NAME: "http://127.0.0.1:6379"
    #   - KEY_HASH_OBJECT: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyY2U3NzdkZTQxMjZlZWYzODlhZGM5ZCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY2MDY0ODEyOSwiaWF0IjoxNjU4MDU2MTI5fQ.g_y-WPtmALc8t-t6-6olgzzgDwH0LauX4j31YnMlFEk 
    #   - RECORD_STREAM_TIME: 15000
    #   - TREACKER_SEARCH_URL : "http://127.0.0.1:9200/face_log/_search"
    #   - SAMPLE_STREAM_URI: "rtsp://172.10.10.220:554/unicast/c0/s0/live"
    #   - WORD_BEFORE_REPLACE_STREAM: c0
    #   - WORD_AFTER_REPLACE_STREAM: c
    #   - KAFKA_BOOTSTRAP:localhost: 9091
    # #   - PORT=${PORT_http}
    #   - MONGO_URL=${MONGODB_URL}
    ports:
      - 9000:3000
    volumes:
      - ./logs:/isss-backend/logs
      - ./assets:/isss-backend/assets
      - ./security:/isss-backend/security

    # external_links:
    #   - mongo1
    #   - mongo2
    #   - mongo3
    #   - redis
    # depends_on:
    #   - mongo1
    #   - mongo2
    #   - mongo3
    #   - redis
# volumes:
#   cache:
#     driver: local
#   mongo-data:
#     driver: local
# volumes:
#   cache:
#     driver: local



# version: '3.7'
# services:
#   backend:
#     container_name: backend
#     image: registry.ariapa.com/isss-backend:latest
#     restart: always
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '9080:3000'
#     environment:
#       API_AI_REDIS_NAME: http://192.168.1.122:23581
#       BASE_URL: 192.168.1.122:9080/api/v1
#       ELASTIC_SEARCH: http://192.168.1.122:9200
#       HOST: 0.0.0.0
#       JWT_SECRET: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY1NzA4ODI5NiwiaWF0IjoxNjU3MDg4Mjk2fQ.0Qoo9fGvlQAQ428j7jJqSKOw9UJK-iXVEdQLwuyYJpg
#       KEY_HASH_OBJECT: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyY2U3NzdkZTQxMjZlZWYzODlhZGM5ZCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY2MDY0ODEyOSwiaWF0IjoxNjU4MDU2MTI5fQ.g_y-WPtmALc8t-t6-6olgzzgDwH0LauX4j31YnMlFEk
#       MONGODB_URL: mongodb://192.168.1.122:27019/test?directConnection=true
#       NODE_ENV: development
#       PORT_http: 3000
#       PORT_https: 4000
#       RECORD_STREAM_TIME: 20000
#       REDIS_URL: redis://192.166.1.122:6379
#       REQUEST_LOG_FILE: ./logs/request.log
#       REQUEST_LOG_FORMAT: dev
#       sample_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyYzY4NGMwNjhiMGNhNjUyNmY3ODkxNCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY1OTc2OTI5MCwiaWF0IjoxNjU3MTc3MjkwfQ.jqWxteAiyQnca22CRaKlHbsjdz-8dfZ0mIMzgaNTSBc
#       TREACKER_SEARCH_URL: http://192.168.1.122:9200/face_log/_search
#       WEB_STREAM: http://127.0.0.1:8083/testcamera/
#       SAMPLE_STREAM_URI: rtsp://172.10.10.220:554/unicast/c0/s0/live
#       WORD_BEFORE_REPLACE_STREAM: c0
#       WORD_AFTER_REPLACE_STREAM: c
#     volumes:
#       - ./logs:/isss-backend/logs
#       - ./assets:/isss-backend/assets
#       - ./security:/isss-backend/security
