
version: "3.7"
services:
  # mongo:
  #   container_name: mongo
  #   image: ${REG}mongo
  #   restart: always
  #   volumes:
  #     - mongo-data:/data
  #   ports:
  #     - 27017:27017
  #  redis:
  #    container_name: redis
  #    image: ${REG}redis
  #   restart: always
  #   volumes: 
  #     - cache:/data
  #   ports:
  #     - 6379:6379
  app:
    container_name: isss-backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    #image: isss-backend
    env_file: .env
    # environment:
    #   - PORT=${PORT_http}
    #   - MONGO_URL=${MONGODB_URL}
    ports:
      - 9000:5000
    volumes:
      - ./logs:/isss-backend/logs
      - ./assets:/isss-backend/assets
      - ./security:/isss-backend/security
#     external_links:
#       - mongo
#       - redis
#     depends_on:
#       - mongo
#       - redis
# volumes:
#   cache:
#     driver: local
#   mongo-data:
#     driver: local