export enum LOG_TYPE_KEYS {
	username = 'username',
	userid = 'userid',
	success = 'success',
	ip = 'ip',
	userAgent = 'userAgent',
	action = 'action',
	method = 'method',
	url = 'url',
	duration = 'duration',
	details = 'details',
	headers = 'headers',
	timestamp = 'timestamp',
	model = 'model',
	recordId = 'recordId',
	component = 'component',
	operation = 'operation',
	license = 'license',
	successEvents = 'successEvents'
}
